discord:
  update-global-commands: true

quarkus:
  log:
    file:
      enabled: true
      path: /export/logs/tortuga/discord/music/server.log
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"