splashArt: """
 _____         _                  _____         _     
|_   _|___ ___| |_ _ _ ___ ___   |     |_ _ ___|_|___ 
  | | | . |  _|  _| | | . | .'|  | | | | | |_ -| |  _|
  |_| |___|_| |_| |___|_  |__,|  |_|_|_|___|___|_|___|
                      |___|                           
"""
discord:
  token: ${DISCORD_TOKEN}