pipeline {
    agent any
    tools {
        maven 'default'
        jdk '21'
    }
    environment {
        TORTUGA_DISCORD_MUSIC_HOST = credentials('tortuga-discord-music-host')
    }
    stages {
        stage('build') {
            steps {
                script {
                    sh 'mvn clean package -pl !jellyfin'
                }
            }
        }
        stage('deploy music') {
            steps {
                script {
                    deploy('music', (String) env.TORTUGA_DISCORD_MUSIC_HOST)
                }
            }
        }
    }
}

def deploy(String project, String host) {
    sh "scp ${project}/target/tortuga-discord-${project}.jar ${host}:/opt/tortuga/discord/${project}"
    sh "ssh ${host} 'sudo systemctl restart tortuga-discord-${project}'"
}