pipeline {
    agent any
    tools {
        maven 'default'
        jdk '21'
    }
    parameters {
        booleanParam(name: 'core', defaultValue: true, description: 'Build tortuga-discord-core')
        booleanParam(name: 'jellyfin', defaultValue: true, description: 'Deploy tortuga-discord-jellyfin')
    }
    environment {
        TORTUGA_DISCORD_JELLYFIN_HOST = credentials('tortuga-discord-jellyfin-host')
    }
    stages {
        stage('build core') {
            when { expression { return params.core } }
            steps {
                script {
                    sh 'mvn -f core clean install'
                }
            }
        }
        stage('build jellyfin') {
            when { expression { return params.jellyfin } }
            steps {
                script {
                    sh 'mvn -f jellyfin clean package'
                }
            }
        }
        stage('deploy jellyfin') {
            when { expression { return params.jellyfin } }
            steps {
                script {
                    deploy('jellyfin', env.TORTUGA_DISCORD_JELLYFIN_HOST)
                }
            }
        }
    }
}

def deploy(String project, String host) {
    sh "scp ${project}/target/tortuga-discord-${project}.jar ${host}:/opt/tortuga/discord/${project}"
    sh "ssh ${host} 'sudo systemctl restart tortuga-discord-${project}'"
}